name: Build WATweaks

on:
  push:
    branches:
      - 'exp2'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  SDK_NAME: iPhoneOS26.2.sdk
  OUTPUT_BASENAME: WATweaks-sdk26.2

jobs:
  build:
    name: build
    runs-on: macos-latest
    permissions:
      contents: write

    steps:
      - name: Checkout